/**
 * Created: 2023-09-01
 * @author Yauhen Saroka <yauhen.saroka@gmail.com>
 */

modded class ActionConstructor
{
    override void RegisterActions(TTypenameArray actions)
    {
        super.RegisterActions(actions);

// = .. :. -%-  .-    .:.................................................................................................................................
// +- :. =  +%.  =.    :::............................................--====-:::::.......................................................................
// .+: -  =  *#.  +    .:-:......................................:-+**++==----:-=:::--------:............................................................
// .:+: -  - .#*  .=   ..:-:..................................-*###**+++=::---.  ...   :--:-=+=..........................................................
// ..-+:.- :: :%+  -:   .:.-:..............................:=+=-::--====--:::.-:::::: -..:---:----.......................................................
// ...=+..: :. =%-  +   : -.-:..........................:==-:-****+=++-:...:--=====----=#=.  .:::-=--....................................................
// ....+= :. -  +%: .+   - =.-:........................== :**+=-..-=: :----:.:--::. .:+-. :==-:.  .-==-..................................................
// .....+= -  =  ##  :=  .- = --......................+:.*=--: :=-:---.   :-=-. :----::-++%-  ..:--:.===-................................................
// .....:+- -  = :%*  =.  =- - -....................:* -*::..++---:    :--:.:--:..-=+**+=*=.*%%%%*+--::-==-:.............................................
// ......:+- - := -%=  +   *..- =...................*.+=.:.=#+=+.   .--..---. :++=:..-+**##=+.  .:----...:=:-:...........................................
// .......-+. : =- +%. .+  .* -.:-.................+:--:.==#*-.    --..==: :++:   .-=:--:.++-++=-----:--...-::-..........................................
// ........=*..: #: ##  :-  -- = +................:+:-:.+*#-.     =..-=:.=*:    ----:::+#%%%%%%%+:   :-+++.::-.=.........................................
// .........++ :::%..%=  =.  =..- =...............+:-..+#+   :   + :=- -#+    -=:-: -##+-::--=##%%*:   .+#*.--:::........................................
// ..........+=:% =* .=.  +  :+ -.::..............*:. =#:  :+.  = :=: =+=   --::..=#: = .::-=--=*%%#-    -%+=-= =........................................
// ..........:+*%* *=  -  .-  == = =.............+:  =#: :=+   +.+=: +=-. :=-:..++::= -   :.---+.+%%=:.   -%#-= =........................................
// ...........-=%%+ #: .:  -. :+:.-.+...........:*  =%:.===  .+.++: *+.: =-: .+#=    =    = =+*.=*%%%..-   *%==:-........................................
// ............+=%%-:%. :   =  :* -.:-..........+: :#-=-=:  :=.*=. **  .=-.-+= :==:  :=   +.=*=-=*:%%#  =  -%+=+.........................................
// .............=+%%.-#  :  .- .=+ = =..........* -+=+-:  :=:.*=..#*  :=-:+*-    ---. --. ++=+-=*  #%*+ =- :*+=+.........................................
// .............:-#%# ++ ..  =  :+::=.=........*==++-  :=-..+#= :#- .--:.#*.      :-:: := +*-+*+   =%**=-= +*=-=.........................................
// ..............=:%%* *- -  .=  -*.=:=......:*%*=. :-=:.:+%+..==.:---.=*-::.      .=:=:.-=:**-   .:%%.++*.#==:-.........................................
// ...............+=%%=.#. -  -. .+= +=+:--+**+--=====+**+-::-=--:::-+*++*#%%%*+-:.  -:--=-#+.:-+#%#%%=+:=+%:==..........................................
// ...............--*%%-:# :.  =  -=+ :#+==#::---=+=#+-:::=---. :===:       .-+#%%%%- .=:=*=*%%#*=:.%%%: =-:===..........................................
// ................=.#%%.=+ -  ::  *=- :=:+    .=:.+:  :--.:=+#%+.   .--==++-:::.:+#-   :-*%*+++*+=*%#*#:%+---*..........................................
// .................=:%%#.*-.-  =  :=+  *=   -=: ==  --:.-+*%%- :*-:  .=#%+*+*+-+..#%-   ++=+++*=%*#%%-.#+#.:=-=-........................................
// .................-:=%%#.#.-. .=  +-*+. -++. :+. -=:-+%%%%%%+   ==--:  :==+=--+.  :-: .%:.:-==+- =%%*-:+-=- .:---:.....................................
// ..................+.#%%+   +  -..=*==**-. .+- :=.=%%##%%*%%++.  .=-.+:::::::.      - .#         -%%#++.:-==::.-:-+--:-+==:............................
// ...................+:%%%+..=++++-=+*-   :+- -+::#%##%=-%#*# =+-   .-=:             :. *         =%%%%+==. .:::::::::::................................
// ...................:-=%%%%#+=:-+++=  :-+= .-+ -%#+*#%*...-*  =:=:    *:          . --:+-       .%%%##%%+++-:..........................................
// ....................+=*=--:.-***+----=-. ::=-*%**#=+%%%+.-%   - .--: =-:       :-:%=   =:      ##%%+..:-=+*=:::.......................................
// .................=++-:=+**###+=::.:--. -===**#*#+.*++*#%%#*.   =   .--:=:      * =+=++=+=     +%=%%%.......+#::=......................................
// ................++=+*+=-:..  .:---. .=+-+*+=*#%- *: .*%%%%-+   -.       =.     .=*+=*#=:     =%%==%%*.......-%-.=.....................................
// ..............:#*+=. .:-=-=--:.:-=+###*+==**#%:.*:  =*%%%%+*.   =        =         :-       -%%%*-:*%+.......+=:-.....................................
// ............:+*=...:==-::-=+**+====+++*####%*.-=  .-+%%%%%#:*   ::       :.   .::-::--:-.  :%%%%%+-.:**:.....--#:.....................................
// +===:....:-=-....:+=:-==:::-=++*#%%####%%%*---. .:+%+%%%%%%.-*.  -:       -.+=++****+==-+..#%%%%%%*::..+-....:=#-.....................................
// .::-++==:.......=+-==..:+#%%#######%%%%*+--:   :=#%=%%%%%%%: :#+. .-:       .-:::  =:-=:..#%%%%%%%%#:-. --...=-*......................................
// ......::=+=--:.+*+=..-*%***#%%%%##**=-...   .:+#%%+%%%%%%%%=   =%*=..:::       :+##**+=::%%%%%%%%%%%#.+. -...--.......................................
// ..........:--=+%#:::+#=+##%#+-:::..      .-+*%%%*+%%%%%%%%%+     =%%#+-::::      .     :%%%%%%%%%%%%%::-..-..-........................................
// ..............=%-::*+==:+==...-:    .-=+#%%%%%**#%%%%#*%#++*      .*%%%%%*==::.       =%%%%%%%%%%%%%%--:.-==-.........................................
// ..............#+:*#=----..-...#-+==-*##%%%****%%%%%%%#=*#%##:.      -#%%%%%%%#**+===+#%%%%%%%%%%%%%%%--..*-...........................................
// ..............#:=#-......-...:* -#==#*%#*#%%%%%%#%%%%- .--=+***+=-.   -#%%%%%%%%###%%%%%%%%%%%%%%%%#+:..+:............................................
// ..............=.+-.......=..=- =%%+#=#+#%%%%%%%#*%%#%-       .::==+**+-:=*%%%%%%%%#**%%%%%%%%%%%%%%--.=+..............................................
// ..............:.:........=-+:=**%++*-=%%%%%%%%#*%%++=---.        ::-==:=#%%%%%%%%%%%%**%%%%%%%%%%%=:-=:...............................................
// ................-......:-+++#**%%=++-#%%%%%%##%%#.  .-=::==-:       :=-----+**+*%%%%%%=%%%%%%%%%*=-...................................................
// .................-=+++++*####%%%%%%%%%%%%%##%%#+       :=. .-++=:.    =:  ..:=#*%%%%%%+%%%%%%#*-:.....................................................
// ...................:=*#####*++==+++++#%%*#%#+=#*=:       --    .-+*=--:==      .%%%%%=:.-++*-:........................................................
// ...............-+++=:     :-==:    :=--++-  .-==**#*-.    .=       :--==+++=-.  -+%#--     =+.........................................................
// ............-*#+--------.     .==:    =--=+.   -=*+**#+=:   +.        .-==*::-=**+-  ::   :=:**+=-=-----:.............................................
// ..........=*=.          :--.     :=-   :=:+=-   .+*.-++====-:+.           =:---=%    :-  :+ .*=%#+=+=+=--==++=-:......................................
// ........=#+::::            :=-.    .=-   +.*-+   -**  :+#*=:.-++-.         -    *-   := += -+ =#=+#++===--.-:-+==--:..................................
// ......-#-     .:---:          -=:    .+. .+.*-+  .##:   .-+%%+-:.-===-.         =#   :+.:.*=.+- -+-#%+--=-- -:.=-=::==:...............................
// ....-*#=-===+++=-: .---.        :=-    -+.-=-*=- .%=+       :=**+===-:-==-:  .  .%.   *=**:-=    .==+%*.-=+- .:.:=-=:=--=:............................
// ...*#+=:        .-+++-.:==-.      .=-.=+*=-*.#:*.-%++.          -=++++===--=++*: *- .+%+--=.       :++%%::=--  .:.=.:.:-.-+-..........................
// ..:%#= :=+=.         -=++-:-=---:---===+-.-+:==:*#%%:=              :=++++=======+#*+-:==.          .=-#%- ==:  =  +  . -::-+-........................
// ..:%-     .=+=:        :-+++++=====*+=.     -#+ *%%%-+                   :-----====---:               :=%%+.-+.  = :: .  :-=--+:......................
// .=++-----:::..-++-.-==-.       :==-      :+%%** :%%%*:-                                                -+%+*=:#  =- =..   -:-=:-=.....................
// *+..   .   ..--. .:.        :==-   .:-=+#%%#- *  %%%%.+.-:.                                           :++%%#* #- .=-.*:. : + =-=:+....................
// #*+++++++=-.   :.        -+=:  :=*#%%%%%*=.   +. #*%%#=*####**+=--:.                              .-++===+%%%= *   -:*   .:=. --=:*:..................
// *=#*#%##%%%%%#*+=-:.     . :=*%%%%**+. +      +. #+*%#++++++++++++=+*+==-:.                    :=+=::+*%%##%%%::=   -:.   .-   :-=**-.................
// %%-...:--=+=+*#%%%%%%#**+*%%%%#+: .*  =       + .%..=%*=--:.  ..:-+++++==+++=---:.         :=++-.:=*+*=.   -%%%=.:   .:::::     :-+-:-=:..............
// %=               .:-+*##%%%%*:   -+  =.       + +#    :.  .:-----:    .-==+*+==----==+==+*+-::-++--+-       -%=%*.          :::::..  ..:=:............
// *=         .:------==+++++-    =*: :+.       +.:%+---:-------:   .-=-:      :-=+++*=-:::..-++=%= ==         .-#:#%#**+=-:. ...::--=--:::::=-..........
// *-+:  :-------=+***+=-.     :+*- :+-       .+.:%+            .-==-.  .-=-.      .-=+==--==-. -* +:        .+  =%-=**%%%%%%%*#%%%####***+===+*-........
// %*=-====+***=-:.       .:-++=. -*+::-----==-.+%*                  :--:   ---.      .-++=.    %.=:        -+ .+*#%#+-..=#%%%%%%%%........:--==+*-......
// %+*++-:.      .:-=++++==++. :+=:::..    .:=*%%=                       ---:: :=-       -=+:  -% +        -+ :*.   =%*--  ++::--#%......................
// %*-.*.  .-====-:.     :+: -#%++++++++*#%%%%%%%:     .=.                  -==-:.==      .=== -# =       .* .*      +%*:+..=.   =%-.....................
// %+::++--:.   ..::----=-.=#%%%%%%%%%%%%%%%%%%%%:   :=:                      .-=-: --.     :+=-* =       +..*        =%#:-=:=:  -%=.....................
// - -:  .:-+*##*+=-:::..=#%%%%%%%%%%%%%%%%%%%%%%:  ==  .------.                 -=-: --     .*-# -      := *.         :%#::*+-=:.%+.....................
// +-+*#%%%*******%%%%%%%*#%%%%%%%%%%%%%%%%%%%%%%  =-          :----.              -==..=.    :+*.       * +-           #%%%%%%=+=%*.....................
//  :+%%#:       +.=+-=--%%%%%%%%%%*=---==*%%%%%- -=                :---.            -=- --    -+-      =::+           -#%*#==#%*=#*.....................
//  *%%+        :: + . -%%%%%%+++=         .#%%+ :*                     :--:          .=+.:=    =#     .= *            ##%=#.  +%%**.....................
// #%#:         = +:  =%%%+.#%%:            *%* .*.                        -==:         =+..=    #:    + =-           =+*%+-=   %%:......................
// %*          = -= .*%%%-...*%%-          =%= .*:                            :==:       =+.:=   -*  .+ -=          .=*-+%# *   *%-......................
// -          -.:* -#%%#:.....+%%*.      -#*. :*-   .::                         .=+:      =+ --   %==- =-          -+-+*#%%*:=  +%=......................
//           .- *-+%%%*........-%**-   :**: .=*-      .==-.                       .++.     += =:  #- -=.          =--##%%%%%+:= =%=......................
//           : ++#%%%=...........+*+*=*+: :-*+.           :-=-.                     -*-     +=.:--%+-.          :=.+#%%%%%*:#*:=+%=......................

        actions.Insert(ActionSearchZombieBodyToViewCargo);
		
        actions.Insert(InediaInfectedAI_ActionOpenDoorQuietly);
        actions.Insert(InediaInfectedAI_ActionCloseDoorQuietly);
		
        actions.Insert(InediaInfectedAI_ActionExtractBulletHeadTarget);
        actions.Insert(InediaInfectedAI_ActionExtractBulletHeadSelf);
        actions.Insert(InediaInfectedAI_ActionExtractBulletArmsTarget);
        actions.Insert(InediaInfectedAI_ActionExtractBulletArmsSelf);
        actions.Insert(InediaInfectedAI_ActionExtractBulletLegsTarget);
        actions.Insert(InediaInfectedAI_ActionExtractBulletLegsSelf);
        actions.Insert(InediaInfectedAI_ActionExtractBulletTorsoTarget);
        actions.Insert(InediaInfectedAI_ActionExtractBulletTorsoSelf);
		
        actions.Insert(InediaInfectedAI_ActionInternalBleedingStopSelf);
        actions.Insert(InediaInfectedAI_ActionInternalBleedingStopTarget);
		
        actions.Insert(InediaInfectedAI_ActionDeepWoundClosureHeadTarget);
        actions.Insert(InediaInfectedAI_ActionDeepWoundClosureHeadSelf);
        actions.Insert(InediaInfectedAI_ActionDeepWoundClosureArmsTarget);
        actions.Insert(InediaInfectedAI_ActionDeepWoundClosureArmsSelf);
        actions.Insert(InediaInfectedAI_ActionDeepWoundClosureLegsTarget);
        actions.Insert(InediaInfectedAI_ActionDeepWoundClosureLegsSelf);
        actions.Insert(InediaInfectedAI_ActionDeepWoundClosureTorsoTarget);
        actions.Insert(InediaInfectedAI_ActionDeepWoundClosureTorsoSelf);
		
		actions.Insert(InediaInfectedAI_ActionDeepWoundBandageHeadTarget);
        actions.Insert(InediaInfectedAI_ActionDeepWoundBandageHeadSelf);
		actions.Insert(InediaInfectedAI_ActionDeepWoundBandageArmsTarget);
        actions.Insert(InediaInfectedAI_ActionDeepWoundBandageArmsSelf);
		actions.Insert(InediaInfectedAI_ActionDeepWoundBandageLegsTarget);
        actions.Insert(InediaInfectedAI_ActionDeepWoundBandageLegsSelf);
        actions.Insert(InediaInfectedAI_ActionDeepWoundBandageTorsoTarget);
        actions.Insert(InediaInfectedAI_ActionDeepWoundBandageTorsoSelf);
		
		actions.Insert(InediaInfectedAI_ActionDeepWoundUnbandageIneffectiveHeadTarget);
        actions.Insert(InediaInfectedAI_ActionDeepWoundUnbandageIneffectiveHeadSelf);
		actions.Insert(InediaInfectedAI_ActionDeepWoundUnbandageIneffectiveArmsTarget);
        actions.Insert(InediaInfectedAI_ActionDeepWoundUnbandageIneffectiveArmsSelf);
		actions.Insert(InediaInfectedAI_ActionDeepWoundUnbandageIneffectiveLegsTarget);
        actions.Insert(InediaInfectedAI_ActionDeepWoundUnbandageIneffectiveLegsSelf);
        actions.Insert(InediaInfectedAI_ActionDeepWoundUnbandageIneffectiveTorsoTarget);
        actions.Insert(InediaInfectedAI_ActionDeepWoundUnbandageIneffectiveTorsoSelf);
		
		actions.Insert(InediaInfectedAI_ActionDeepWoundUnbandageEffectiveHeadTarget);
        actions.Insert(InediaInfectedAI_ActionDeepWoundUnbandageEffectiveHeadSelf);
		actions.Insert(InediaInfectedAI_ActionDeepWoundUnbandageEffectiveArmsTarget);
        actions.Insert(InediaInfectedAI_ActionDeepWoundUnbandageEffectiveArmsSelf);
		actions.Insert(InediaInfectedAI_ActionDeepWoundUnbandageEffectiveLegsTarget);
        actions.Insert(InediaInfectedAI_ActionDeepWoundUnbandageEffectiveLegsSelf);
        actions.Insert(InediaInfectedAI_ActionDeepWoundUnbandageEffectiveTorsoTarget);
        actions.Insert(InediaInfectedAI_ActionDeepWoundUnbandageEffectiveTorsoSelf);
		
		actions.Insert(InediaInfectedAI_ActionFractureStabilizationHeadTarget);
		actions.Insert(InediaInfectedAI_ActionFractureStabilizationHeadSelf);
		actions.Insert(InediaInfectedAI_ActionFractureStabilizationArmsTarget);
		actions.Insert(InediaInfectedAI_ActionFractureStabilizationArmsSelf);
		actions.Insert(InediaInfectedAI_ActionFractureStabilizationLegsTarget);
		actions.Insert(InediaInfectedAI_ActionFractureStabilizationLegsSelf);
		actions.Insert(InediaInfectedAI_ActionFractureStabilizationTorsoTarget);
		actions.Insert(InediaInfectedAI_ActionFractureStabilizationTorsoSelf);
        actions.Insert(InediaInfectedAI_ActionFractureUnstabilizationHeadTarget);
        actions.Insert(InediaInfectedAI_ActionFractureUnstabilizationHeadSelf);
        actions.Insert(InediaInfectedAI_ActionFractureUnstabilizationArmsTarget);
        actions.Insert(InediaInfectedAI_ActionFractureUnstabilizationArmsSelf);
        actions.Insert(InediaInfectedAI_ActionFractureUnstabilizationLegsTarget);
        actions.Insert(InediaInfectedAI_ActionFractureUnstabilizationLegsSelf);
        actions.Insert(InediaInfectedAI_ActionFractureUnstabilizationTorsoTarget);
        actions.Insert(InediaInfectedAI_ActionFractureUnstabilizationTorsoSelf);
		
        actions.Insert(InediaInfectedAI_ActionCutClosureTarget);
        actions.Insert(InediaInfectedAI_ActionCutClosureSelf);
		
		actions.Insert(InediaInfectedAI_ActionUseSelf);
		actions.Insert(InediaInfectedAI_ActionUseTarget);
    }
};

// sLyuegMz2M+HjD/LrN5baU1HcndlRGxxcHpqLzE5RnR6ZGJoQUROaTFzWFJsUnZNME5XajhoNFRIWDhYR0trTm1rRkZKNFhOdWtNdWlDaWNXMWVLbXE1dlh6Mzl4WUFXSUdiZ2VVNS82ZlNHcFcxYUlqcDNTN1c3eTI3NXc0bTUxaVlRc2ZGUkJJdHFIQzhndzJFTFdtR2YxZVl2RklTZjB4cmFtaWtLY2t5RG1rUnUycEJKdDE0by9FUHpYTCtXMEJEUEN4ZlVjZVowcXpWWC81b0J4TUNhRkRJU0R0Z1Ztd2VncWVYTGt5ZkNnMGp2Uk45SFdWaVpxMjh4bTc1RzRmQnp4Z056VkVNWGQ3bVU1YjlVZ1Uvc0ZqUTJmVFJBY1FPMnJBPT0=
